import { IVideo, ISettings } from './types';

/**
 * Curated production-ready video catalog used for instant initial hydration,
 * Supabase cold-start tolerance, offline mode, and fail-safe API fallbacks.
 */
export const CURATED_FALLBACK_VIDEOS: IVideo[] = [
  {
    _id: 'vid-neon-protocol-4k',
    title: 'Neon Protocol: Cyber Shadow',
    description: 'A rogue neural net hacker discovers an encrypted corporate conspiracy deep inside the neo-Tokyo megagrid. High-bitrate 4K stream.',
    posterUrl: '/images/hero_viral_cyberpunk.jpg',
    bannerGifUrl: '/images/hero_viral_cyberpunk.jpg',
    bannerUrl: '/images/hero_viral_cyberpunk.jpg',
    category: 'Trending',
    streamUrl: 'https://fastcdn.stream/v/demo-neon-protocol',
    serverUrl: 'https://fastcdn.stream/v/demo-neon-protocol',
    hdSourceUrl: 'https://fastcdn.stream/v/demo-neon-protocol',
    targetLink: 'https://fastcdn.stream/v/demo-neon-protocol',
    targetType: 'direct_stream',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 2,
    viewsCount: 48920,
    isFeatured: true,
    fileSize: '1.8 GB',
    quality: '4K Ultra HD',
    tags: ['Cyberpunk', 'Sci-Fi', 'Thriller', 'VIP Master'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'vid-shadow-heist-1080p',
    title: 'Shadow Heist: Dark Protocol',
    description: 'A seasoned crew of black-ops specialists plan the infiltration of a sovereign underground vault in Geneva.',
    posterUrl: '/images/movie_action_heist.jpg',
    bannerGifUrl: '/images/movie_action_heist.jpg',
    bannerUrl: '/images/movie_action_heist.jpg',
    category: 'Action',
    streamUrl: 'https://fastcdn.stream/v/demo-shadow-heist',
    serverUrl: 'https://fastcdn.stream/v/demo-shadow-heist',
    hdSourceUrl: 'https://fastcdn.stream/v/demo-shadow-heist',
    targetLink: 'https://fastcdn.stream/v/demo-shadow-heist',
    targetType: 'direct_stream',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 2,
    viewsCount: 29400,
    isFeatured: false,
    fileSize: '1.4 GB',
    quality: '1080p HD',
    tags: ['Action', 'Heist', 'Crime'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'vid-celestial-blade-hd',
    title: 'Celestial Blade: Sovereign Chronicle',
    description: 'In ancient celestial realms, legendary blade masters fight to preserve cosmic balance against shadow dragons.',
    posterUrl: '/images/movie_anime_fantasy.jpg',
    bannerGifUrl: '/images/movie_anime_fantasy.jpg',
    bannerUrl: '/images/movie_anime_fantasy.jpg',
    category: 'Anime',
    streamUrl: 'https://fastcdn.stream/v/demo-celestial-blade',
    serverUrl: 'https://fastcdn.stream/v/demo-celestial-blade',
    hdSourceUrl: 'https://fastcdn.stream/v/demo-celestial-blade',
    targetLink: 'https://fastcdn.stream/v/demo-celestial-blade',
    targetType: 'direct_stream',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 1,
    viewsCount: 42100,
    isFeatured: false,
    fileSize: '1.2 GB',
    quality: '1080p Dual Audio',
    tags: ['Anime', 'Fantasy', 'Action', 'Cultivation'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'vid-dark-net-syndicate',
    title: 'The Dark Net Syndicate: Exposed',
    description: 'Investigative documentary deep dive into covert offshore server clusters, zero-day exploit markets, and encrypted data leaks.',
    posterUrl: '/images/movie_viral_documentary.jpg',
    bannerGifUrl: '/images/movie_viral_documentary.jpg',
    bannerUrl: '/images/movie_viral_documentary.jpg',
    category: 'Viral Clips',
    streamUrl: 'https://fastcdn.stream/v/demo-dark-net',
    serverUrl: 'https://fastcdn.stream/v/demo-dark-net',
    hdSourceUrl: 'https://fastcdn.stream/v/demo-dark-net',
    targetLink: 'https://fastcdn.stream/v/demo-dark-net',
    targetType: 'direct_stream',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 2,
    viewsCount: 63800,
    isFeatured: false,
    fileSize: '950 MB',
    quality: '1080p HD',
    tags: ['Documentary', 'Viral Leak', 'Tech'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'vid-terabox-vault-exclusive',
    title: 'Terabox Cloud Vault: Fast Mirror 2026',
    description: 'Exclusive multi-part high speed 4K mirror package with direct streaming support and instant unthrottled downloads.',
    posterUrl: '/images/hero_viral_cyberpunk.jpg',
    bannerGifUrl: '/images/hero_viral_cyberpunk.jpg',
    bannerUrl: '/images/hero_viral_cyberpunk.jpg',
    category: 'Terabox Exclusives',
    streamUrl: 'https://fastcdn.stream/v/terabox-vault-mirror',
    serverUrl: 'https://fastcdn.stream/v/terabox-vault-mirror',
    hdSourceUrl: 'https://fastcdn.stream/v/terabox-vault-mirror',
    targetLink: 'https://fastcdn.stream/v/terabox-vault-mirror',
    targetType: 'terabox',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 2,
    viewsCount: 31200,
    isFeatured: false,
    fileSize: '3.2 GB',
    quality: '4K Remux',
    tags: ['Terabox', 'Cloud', 'Exclusive', 'Mirror'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'vid-apex-velocity-racing',
    title: 'Apex Velocity: Midnight Rush',
    description: 'Underground illegal street races spanning the neon mountain passes of Hakone with heavily modified prototypes.',
    posterUrl: '/images/movie_action_heist.jpg',
    bannerGifUrl: '/images/movie_action_heist.jpg',
    bannerUrl: '/images/movie_action_heist.jpg',
    category: 'Viral Movies',
    streamUrl: 'https://fastcdn.stream/v/demo-apex-velocity',
    serverUrl: 'https://fastcdn.stream/v/demo-apex-velocity',
    hdSourceUrl: 'https://fastcdn.stream/v/demo-apex-velocity',
    targetLink: 'https://fastcdn.stream/v/demo-apex-velocity',
    targetType: 'direct_stream',
    directAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
    requiredAdsCount: 2,
    viewsCount: 21900,
    isFeatured: false,
    fileSize: '1.6 GB',
    quality: '1080p 60fps',
    tags: ['Racing', 'Action', 'Adrenaline'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const DEFAULT_APP_SETTINGS: ISettings = {
  appName: 'VIRAL LINK HUB',
  maintenanceMode: false,
  globalAdLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
  primaryDirectLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
  secondaryDirectLink: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
  defaultAdsRequired: 2,
  announcementBannerText: '🔥 High-Speed Direct Cloud Streams active! Complete sponsor task to unlock.',
  telegramChannelUrl: 'https://t.me/virallinkhub_official',
  forceJoinChannel: false,
  isMaintenanceBypassAllowed: true,
  // Monetag
  monetagZoneId: '11955914',
  monetagEnabled: true,
  inAppFrequency: 2,
  inAppCapping: 0.1,
  inAppInterval: 30,
  inAppTimeout: 5,
  // Adsterra
  adsterraEnabled: true,
  adsterraPopunderUrl: 'https://cheflobesofficer.com/26/24/93/262493230301da17c67cbcf5a1d5e15b.js',
  adsterraSmartlinkUrl: 'https://cheflobesofficer.com/cvdp4vvsma?key=fbecdf734cc50866fb1dcfa342c33a86',
  adsterraSocialBarUrl: 'https://cheflobesofficer.com/db/ca/37/dbca37a0ea14e2da7c5826f0a5e6fbb9.js',
  adsterraNativeBannerUrl: 'https://cheflobesofficer.com/5f7e7c20bab3c9a4fa6f40424b458934/invoke.js',
  adsterraNativeBannerContainer: 'container-5f7e7c20bab3c9a4fa6f40424b458934',
  adsterraBanner728x90Key: 'd2a5e27ec28fef3e096f82c41992173b',
  // Frequency & Controls
  premiumRewardEnabled: true,
  premiumRequiredAds: 3,
  premiumRequiredReferrals: 3,
  premiumDurationHours: 24,
  adCooldownSeconds: 10,
  maxAdsPerSession: 5,
  maxPopundersPerSession: 1,
  maxAdsPerDay: 30,
  adPlacements: {
    homeBanner: true,
    contentCard: true,
    contentDetails: true,
    unlockAction: true,
    betweenNav: true,
    popunder: true,
    premiumRewardArea: true,
    nativeBannerHome: true,
    nativeBannerContent: true,
    banner728x90Desktop: true,
    socialBarGlobal: true,
    popunderGlobal: true,
    monetagRewarded: true,
    monetagInApp: true,
  },
  // Professional Intro / Hero & Community Section
  introTitle: 'Unlimited Cloud Entertainment & Instant Streaming',
  introSubtitle: 'VIP Fast-Track Access · Official Telegram Community Hub',
  introDescription:
    'Discover exclusive high-speed cloud movies, viral anime releases, and direct VIP links. Join our verified Telegram ecosystem to unlock 4K content with instant direct access.',
  introPrimaryCtaText: 'Join Official Community',
  introPrimaryCtaUrl: 'https://t.me/virallinkhub_official',
  introSecondaryCtaText: 'Browse Movies',
  introSecondaryCtaUrl: '#browse-catalog',
  communitySectionTitle: 'Official Telegram Ecosystem',
  communitySectionSubtitle:
    'Join our verified channels, discussion groups, and interactive bots for direct links and member-only updates',
  showIntroHero: true,
};

/**
 * Initial production-ready Telegram destinations
 * Manages 6 official channels, groups, and bots across Website and Mini App.
 */
export const INITIAL_TELEGRAM_DESTINATIONS: import('./types').ITelegramDestination[] = [
  {
    id: 'tg-dest-announcements-official',
    title: 'Viral Link Hub · Official Announcements',
    description: 'Daily direct cloud releases, 4K movies, server status & exclusive VIP links.',
    type: 'channel',
    url: 'https://t.me/virallinkhub_official',
    username: '@virallinkhub_official',
    chatId: '@virallinkhub_official',
    icon: 'bell',
    isRequired: true,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 1,
    isActive: true,
    memberCountDisplay: '54.2K members',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tg-dest-vip-requests-group',
    title: 'VIP Community & Movie Requests',
    description: 'Chat with 18,000+ members, request viral movies, and share cloud direct links.',
    type: 'group',
    url: 'https://t.me/virallinkhub_chat',
    username: '@virallinkhub_chat',
    chatId: '@virallinkhub_chat',
    icon: 'message-circle',
    isRequired: false,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 2,
    isActive: true,
    memberCountDisplay: '18.4K members',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tg-dest-cloud-delivery-bot',
    title: 'FastCloud Stream & Notification Bot',
    description: 'Instant high-speed stream link generator & one-click cloud file delivery.',
    type: 'bot',
    url: 'https://t.me/viral_link_hub_free_bot',
    username: '@viral_link_hub_free_bot',
    chatId: '',
    icon: 'bot',
    isRequired: true,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 3,
    isActive: true,
    memberCountDisplay: 'Active 24/7',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tg-dest-anime-fantasy-channel',
    title: 'Anime & Cultivation HD Releases',
    description: 'Dedicated subbed anime episodes, uncensored cuts, and 60fps high bitrate encodes.',
    type: 'channel',
    url: 'https://t.me/virallinkhub_anime',
    username: '@virallinkhub_anime',
    chatId: '@virallinkhub_anime',
    icon: 'sparkles',
    isRequired: false,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 4,
    isActive: true,
    memberCountDisplay: '32.1K members',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tg-dest-bypass-tool-bot',
    title: 'Terabox Cloud Link Bypass Bot',
    description: 'Auto-extract direct video streams from any Terabox or cloud storage share URL.',
    type: 'bot',
    url: 'https://t.me/virallinkhub_bypass_bot',
    username: '@virallinkhub_bypass_bot',
    chatId: '',
    icon: 'shield',
    isRequired: false,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 5,
    isActive: true,
    memberCountDisplay: 'Free Tool',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tg-dest-global-discussion-group',
    title: 'Global Cinema Discussion & Spoilers',
    description: 'International movie enthusiasts, review threads, recommendations, and ratings.',
    type: 'group',
    url: 'https://t.me/virallinkhub_global',
    username: '@virallinkhub_global',
    chatId: '@virallinkhub_global',
    icon: 'send',
    isRequired: false,
    showOnWebsite: true,
    showOnMiniapp: true,
    orderIndex: 6,
    isActive: true,
    memberCountDisplay: '12.8K members',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
